// ============================================
// Queen International School - Real Employee Data
// ============================================

import { Employee } from '../types';
import { generateId } from './employeeService';
import { addRecordsBulk, getAllRecords } from './db';

const sampleEmployees: Omit<Employee, 'id' | 'employeeCode' | 'createdAt' | 'updatedAt'>[] = [
  { fullName:'AYMIN ABDALLA', arabicName:'ايمن عبدالله', title:'Teacher', nationality:'Egyptian', contactNumber:'+971 50 765 3442', emirateId:'', passportNumber:'A29585111', passportIssueDate:'', passportExpiryDate:'2028-02-18', visaExpiryDate:'2027-06-18', labourExpiry:'2027-08-20', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2500, otherAllowance:5400, totalSalary:7900 },
  { fullName:'ARMUGAM NALLASIVAM', arabicName:'أرموجام نالاسيفام', title:'Teacher', nationality:'Indian', contactNumber:'+971 55 294 0036', emirateId:'', passportNumber:'L4130609', passportIssueDate:'', passportExpiryDate:'2033-07-19', visaExpiryDate:'2026-08-28', labourExpiry:'2026-08-15', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:6000, totalSalary:8000 },
  { fullName:'GRETA DUFFIELD', arabicName:'غريتا دوفيلد', title:'Teacher', nationality:'American', contactNumber:'+971 50 443 0530', emirateId:'', passportNumber:'567877119', passportIssueDate:'', passportExpiryDate:'2030-02-13', visaExpiryDate:'2026-08-28', labourExpiry:'2028-06-30', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:3000, otherAllowance:8400, totalSalary:11400 },
  { fullName:'MERVAT HASHEM ALI', arabicName:'ميرفت هاشم علي', title:'Teacher', nationality:'Syrian', contactNumber:'+971 50 483 1710', emirateId:'', passportNumber:'NO15659015', passportIssueDate:'', passportExpiryDate:'2028-07-24', visaExpiryDate:'2027-10-10', labourExpiry:'2027-09-30', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2500, otherAllowance:3700, totalSalary:6200 },
  { fullName:'REMESH BABU', arabicName:'ريميش بابو', title:'Teacher', nationality:'Indian', contactNumber:'+971 50 676 1755', emirateId:'', passportNumber:'Z4980454', passportIssueDate:'', passportExpiryDate:'2028-12-16', visaExpiryDate:'2027-02-26', labourExpiry:'2027-03-12', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:3000, otherAllowance:7900, totalSalary:10900 },
  { fullName:'RIMA RADWAN', arabicName:'ريما رضوان', title:'Teacher', nationality:'Syrian', contactNumber:'+971 55 958 1357', emirateId:'', passportNumber:'N007887613', passportIssueDate:'', passportExpiryDate:'2031-03-19', visaExpiryDate:'2027-09-25', labourExpiry:'2027-09-26', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2500, otherAllowance:4300, totalSalary:6800 },
  { fullName:'SAJAN GEORGE', arabicName:'ساجن جارج', title:'Teacher', nationality:'Indian', contactNumber:'+971 50 788 4246', emirateId:'', passportNumber:'Z3722677', passportIssueDate:'', passportExpiryDate:'2027-04-26', visaExpiryDate:'2027-08-30', labourExpiry:'2027-07-11', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:3000, otherAllowance:6900, totalSalary:9900 },
  { fullName:'SAMAH GOUDA', arabicName:'سماح جودة', title:'Teacher', nationality:'Egyptian', contactNumber:'+971 50 201 0846', emirateId:'', passportNumber:'A13850147', passportIssueDate:'', passportExpiryDate:'2028-07-28', visaExpiryDate:'2027-11-25', labourExpiry:'2027-12-02', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:6100, totalSalary:8100 },
  { fullName:'PENINA NYABOKE', arabicName:'بينينا نيابوكي', title:'Teacher', nationality:'Kenyan', contactNumber:'', emirateId:'', passportNumber:'A2472026', passportIssueDate:'', passportExpiryDate:'2028-07-31', visaExpiryDate:'2026-08-27', labourExpiry:'2026-08-16', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:3650, totalSalary:5650 },
  { fullName:'SUCHETA KADER', arabicName:'سوشيتا قادر', title:'Teacher', nationality:'Indian', contactNumber:'', emirateId:'', passportNumber:'UO826083', passportIssueDate:'', passportExpiryDate:'2030-09-05', visaExpiryDate:'2027-01-17', labourExpiry:'2027-01-11', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2500, otherAllowance:4400, totalSalary:6900 },
  { fullName:'LOTFI ABDELKADER', arabicName:'لطفي عبد القادر', title:'Teacher', nationality:'Egyptian', contactNumber:'+971 52 566 8087', emirateId:'', passportNumber:'A31038483', passportIssueDate:'', passportExpiryDate:'2029-07-20', visaExpiryDate:'2027-08-31', labourExpiry:'2027-09-06', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:3400, totalSalary:5400 },
  { fullName:'NEVINE MAMDOUH', arabicName:'نيفين مامدوح', title:'Teacher', nationality:'Egyptian', contactNumber:'+971 50 634 1059', emirateId:'', passportNumber:'A21106217', passportIssueDate:'', passportExpiryDate:'2031-07-15', visaExpiryDate:'2027-11-10', labourExpiry:'2027-11-09', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:3000, otherAllowance:2600, totalSalary:5600 },
  { fullName:'FALASTINE OTHMAN', arabicName:'فلسطين عثمان', title:'Teacher', nationality:'Jordanian', contactNumber:'', emirateId:'', passportNumber:'Q988186', passportIssueDate:'', passportExpiryDate:'2027-05-08', visaExpiryDate:'2026-06-18', labourExpiry:'2028-05-30', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:3700, totalSalary:5700 },
  { fullName:'IZABELLA MALOGORZATA', arabicName:'إيزابيلا مالوجورزاتا', title:'Teacher', nationality:'Other', contactNumber:'+971 55 551 7933', emirateId:'', passportNumber:'EA2411170', passportIssueDate:'', passportExpiryDate:'2029-07-16', visaExpiryDate:'2026-11-16', labourExpiry:'2026-11-10', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2500, otherAllowance:10000, totalSalary:12500 },
  { fullName:'SAPNA JAVED', arabicName:'سابنا جافيد', title:'Teacher', nationality:'Pakistani', contactNumber:'', emirateId:'', passportNumber:'SQ19877444', passportIssueDate:'', passportExpiryDate:'2034-04-18', visaExpiryDate:'2026-08-27', labourExpiry:'2026-09-06', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:4000, totalSalary:6000 },
  { fullName:'DASA GABRISOVA', arabicName:'داسا غابريسوفا', title:'Teacher', nationality:'Other', contactNumber:'+971 52 977 6585', emirateId:'', passportNumber:'BA4220189', passportIssueDate:'', passportExpiryDate:'2028-07-24', visaExpiryDate:'2026-11-06', labourExpiry:'2026-10-31', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2500, otherAllowance:7500, totalSalary:10000 },
  { fullName:'SUSAN JOHN', arabicName:'سوزان جون', title:'Teacher', nationality:'Indian', contactNumber:'+971 50 564 4303', emirateId:'', passportNumber:'L8601396', passportIssueDate:'', passportExpiryDate:'2034-03-14', visaExpiryDate:'2026-11-28', labourExpiry:'2027-01-19', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:3000, otherAllowance:8000, totalSalary:11000 },
  { fullName:'LINET AKINY', arabicName:'لينيت أكيني', title:'Teacher', nationality:'Kenyan', contactNumber:'+971 50 827 2318', emirateId:'', passportNumber:'AK0149579', passportIssueDate:'', passportExpiryDate:'2028-07-09', visaExpiryDate:'2027-09-18', labourExpiry:'2027-09-12', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:2500, totalSalary:4500 },
  { fullName:'LORRAINE CHEMTAI', arabicName:'لورين شيمتاي', title:'Teacher', nationality:'Kenyan', contactNumber:'+971 50 302 4219', emirateId:'', passportNumber:'AK0527344', passportIssueDate:'', passportExpiryDate:'2029-09-01', visaExpiryDate:'2027-09-18', labourExpiry:'2027-09-12', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:3000, totalSalary:5000 },
  { fullName:'LOCY WAITHERA', arabicName:'لوسي وايثيرا', title:'Teacher', nationality:'Kenyan', contactNumber:'+971 56 682 4120', emirateId:'', passportNumber:'AK0434314', passportIssueDate:'', passportExpiryDate:'2029-07-16', visaExpiryDate:'2027-09-18', labourExpiry:'2027-09-12', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:4200, totalSalary:6200 },
  { fullName:'ELMA SANIA', arabicName:'إلما سانيا', title:'Teacher', nationality:'South African', contactNumber:'', emirateId:'', passportNumber:'M00142746', passportIssueDate:'', passportExpiryDate:'2034-12-19', visaExpiryDate:'2027-11-07', labourExpiry:'2027-11-01', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:3000, otherAllowance:2000, totalSalary:5000 },
  { fullName:'RENITHA DIVAKARAN', arabicName:'رينيتا ديفاكاران', title:'Teacher', nationality:'Indian', contactNumber:'', emirateId:'', passportNumber:'V6166486', passportIssueDate:'', passportExpiryDate:'2032-01-24', visaExpiryDate:'2026-08-27', labourExpiry:'2026-09-03', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:6000, totalSalary:8000 },
  { fullName:'AHMED ABDALMOHSEN', arabicName:'أحمد عبد المحسن', title:'Teacher', nationality:'Egyptian', contactNumber:'', emirateId:'', passportNumber:'A27009343', passportIssueDate:'', passportExpiryDate:'2027-06-03', visaExpiryDate:'2026-10-11', labourExpiry:'2026-10-12', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2500, otherAllowance:3500, totalSalary:6000 },
  { fullName:'SHIBY MOL', arabicName:'شيبي مول', title:'Teacher', nationality:'Indian', contactNumber:'', emirateId:'', passportNumber:'S9936774', passportIssueDate:'', passportExpiryDate:'2029-03-21', visaExpiryDate:'2028-04-20', labourExpiry:'2028-04-04', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:3500, totalSalary:5500 },
  { fullName:'NIDA SHAUKAT', arabicName:'ندى شوكت', title:'Teacher', nationality:'Pakistani', contactNumber:'+971 55 778 8135', emirateId:'', passportNumber:'BY5197414', passportIssueDate:'', passportExpiryDate:'2032-09-28', visaExpiryDate:'2027-09-24', labourExpiry:'2027-09-16', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2500, otherAllowance:5500, totalSalary:8000 },
  { fullName:'MOHMOUD AHMED', arabicName:'محمود أحمد', title:'PE Teacher', nationality:'Egyptian', contactNumber:'', emirateId:'', passportNumber:'A35396455', passportIssueDate:'', passportExpiryDate:'2030-10-09', visaExpiryDate:'2026-09-12', labourExpiry:'2026-09-09', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2500, otherAllowance:2500, totalSalary:5000 },
  { fullName:'SARA WALED', arabicName:'سارة وليد', title:'PE Teacher', nationality:'Egyptian', contactNumber:'', emirateId:'', passportNumber:'A34244858', passportIssueDate:'', passportExpiryDate:'2030-06-12', visaExpiryDate:'2026-09-19', labourExpiry:'2026-09-10', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:2500, totalSalary:4500 },
  { fullName:'SYLVESTER XAVIER', arabicName:'سيلفستر كزافييه', title:'Teacher', nationality:'Indian', contactNumber:'', emirateId:'', passportNumber:'NO255771', passportIssueDate:'', passportExpiryDate:'2035-09-29', visaExpiryDate:'2026-11-17', labourExpiry:'2026-11-14', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:3000, otherAllowance:6000, totalSalary:9000 },
  { fullName:'LISKE HARTZENBERG', arabicName:'ليسكي هارتزنبرغ', title:'Teacher', nationality:'South African', contactNumber:'', emirateId:'', passportNumber:'A10015136', passportIssueDate:'', passportExpiryDate:'2032-11-09', visaExpiryDate:'2027-09-18', labourExpiry:'2027-08-23', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:4000, totalSalary:6000 },
  { fullName:'FADIA SHAKLAB', arabicName:'فادية شكلاب', title:'Vice Principal', nationality:'Syrian', contactNumber:'', emirateId:'', passportNumber:'N001151249', passportIssueDate:'', passportExpiryDate:'2029-07-03', visaExpiryDate:'2026-11-06', labourExpiry:'2027-01-13', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:3000, otherAllowance:11800, totalSalary:14800 },
  { fullName:'LAMA ALAA ELDIN', arabicName:'لما علاء الدين', title:'Staff', nationality:'Syrian', contactNumber:'', emirateId:'', passportNumber:'NO15738537', passportIssueDate:'', passportExpiryDate:'2028-08-14', visaExpiryDate:'2027-08-19', labourExpiry:'2027-11-28', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:5000, otherAllowance:5500, totalSalary:10500 },
  { fullName:'ABDEL HAMEED', arabicName:'عبد الحميد', title:'Staff', nationality:'Sri Lankan', contactNumber:'', emirateId:'', passportNumber:'N6310983', passportIssueDate:'', passportExpiryDate:'2030-05-17', visaExpiryDate:'2026-08-27', labourExpiry:'2026-09-08', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:1000, otherAllowance:3600, totalSalary:4600 },
  { fullName:'MILDRED BAIDE', arabicName:'ميلدريد بايد', title:'Staff', nationality:'Filipino', contactNumber:'', emirateId:'', passportNumber:'P5184124B', passportIssueDate:'', passportExpiryDate:'2030-05-17', visaExpiryDate:'2027-12-05', labourExpiry:'2027-12-01', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:2000, totalSalary:4000 },
  { fullName:'FARAH FATEH', arabicName:'فرح فاتح', title:'Staff', nationality:'Syrian', contactNumber:'', emirateId:'', passportNumber:'NO15655028', passportIssueDate:'', passportExpiryDate:'2028-07-16', visaExpiryDate:'2026-09-19', labourExpiry:'2026-09-14', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:2300, totalSalary:4300 },
  { fullName:'ADNAN PUTHUSSERI', arabicName:'عدنان بوثوسيري', title:'Staff', nationality:'Indian', contactNumber:'', emirateId:'', passportNumber:'N8159683', passportIssueDate:'', passportExpiryDate:'2036-06-06', visaExpiryDate:'2027-02-26', labourExpiry:'2027-02-22', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:3000, totalSalary:5000 },
  { fullName:'AMIR KHAN', arabicName:'أمير خان', title:'Driver', nationality:'Pakistani', contactNumber:'', emirateId:'', passportNumber:'EA4147892', passportIssueDate:'', passportExpiryDate:'2028-12-29', visaExpiryDate:'2028-05-07', labourExpiry:'2028-05-22', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:1200, otherAllowance:350, totalSalary:1550 },
  { fullName:'HASHIM KHAN', arabicName:'هاشم خان', title:'Driver', nationality:'Pakistani', contactNumber:'', emirateId:'', passportNumber:'CK4108944', passportIssueDate:'', passportExpiryDate:'2029-08-21', visaExpiryDate:'2026-11-15', labourExpiry:'2026-11-19', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:1500, otherAllowance:1050, totalSalary:2550 },
  { fullName:'KHAN FAREZ', arabicName:'خان فاريز', title:'Driver', nationality:'Pakistani', contactNumber:'', emirateId:'', passportNumber:'BE8919524', passportIssueDate:'', passportExpiryDate:'2032-08-26', visaExpiryDate:'2027-10-29', labourExpiry:'2027-11-06', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'77', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:1500, otherAllowance:1050, totalSalary:2550 },
  { fullName:'MOHAMMAD ISHAQ', arabicName:'محمد إسحاق', title:'Driver', nationality:'Pakistani', contactNumber:'+971 50 578 9417', emirateId:'', passportNumber:'P14103883', passportIssueDate:'', passportExpiryDate:'2026-11-18', visaExpiryDate:'2028-05-08', labourExpiry:'2028-06-15', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'45', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2100, otherAllowance:3750, totalSalary:5850 },
  { fullName:'MOHAMMAD FAROOQ', arabicName:'محمد فاروق', title:'Driver', nationality:'Pakistani', contactNumber:'+971 50 778 7591', emirateId:'', passportNumber:'DC8967604', passportIssueDate:'', passportExpiryDate:'2027-08-02', visaExpiryDate:'2027-01-11', labourExpiry:'2027-01-28', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:3000, totalSalary:5000 },
  { fullName:'MOHAD AHMED SALEEM', arabicName:'محمد أحمد سليم', title:'Driver', nationality:'Pakistani', contactNumber:'+971 50 321 3702', emirateId:'', passportNumber:'RE1156893', passportIssueDate:'', passportExpiryDate:'2033-02-12', visaExpiryDate:'2027-04-20', labourExpiry:'2027-04-18', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:1500, otherAllowance:1050, totalSalary:2550 },
  { fullName:'YAQOOB KHAN', arabicName:'يعقوب خان', title:'Driver', nationality:'Pakistani', contactNumber:'+971 50 765 9921', emirateId:'', passportNumber:'FC4111012', passportIssueDate:'', passportExpiryDate:'2034-03-31', visaExpiryDate:'2027-10-30', labourExpiry:'2027-10-18', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:1500, otherAllowance:1050, totalSalary:2550 },
  { fullName:'TAHER IQBAL', arabicName:'طاهر إقبال', title:'Driver', nationality:'Pakistani', contactNumber:'+971 50 856 4699', emirateId:'', passportNumber:'CC1335605', passportIssueDate:'', passportExpiryDate:'2035-11-16', visaExpiryDate:'2026-06-09', labourExpiry:'2026-06-18', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:1500, otherAllowance:1050, totalSalary:2550 },
  { fullName:'MOHMMAD WAQAS', arabicName:'محمد وقاص', title:'Driver', nationality:'Pakistani', contactNumber:'+971 56 193 7380', emirateId:'', passportNumber:'BF6311613', passportIssueDate:'', passportExpiryDate:'2034-02-13', visaExpiryDate:'2027-03-08', labourExpiry:'2027-03-05', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:1500, otherAllowance:1000, totalSalary:2500 },
  { fullName:'CORNELLIA BARSAMINA', arabicName:'كورنيليا بارسامينا', title:'Labour', nationality:'Filipino', contactNumber:'', emirateId:'', passportNumber:'P5639089A', passportIssueDate:'', passportExpiryDate:'2028-01-16', visaExpiryDate:'2026-11-15', labourExpiry:'2026-11-16', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:750, otherAllowance:1550, totalSalary:2300 },
  { fullName:'JENNIFER LINGKIAT', arabicName:'جينيفر لينغكيات', title:'Labour', nationality:'Filipino', contactNumber:'', emirateId:'', passportNumber:'P9206511A', passportIssueDate:'', passportExpiryDate:'2028-10-17', visaExpiryDate:'2026-08-28', labourExpiry:'2026-11-06', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:750, otherAllowance:750, totalSalary:1500 },
  { fullName:'NIDA BERSAMINA', arabicName:'نيدا بيرسامينا', title:'Labour', nationality:'Filipino', contactNumber:'', emirateId:'', passportNumber:'P9202659A', passportIssueDate:'', passportExpiryDate:'2028-10-17', visaExpiryDate:'2026-08-28', labourExpiry:'2026-09-02', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:750, otherAllowance:650, totalSalary:1400 },
  { fullName:'ROSELA ORTEGA', arabicName:'روزيلا أورتيغا', title:'Labour', nationality:'Filipino', contactNumber:'', emirateId:'', passportNumber:'P6587380D', passportIssueDate:'', passportExpiryDate:'2031-03-18', visaExpiryDate:'2027-09-02', labourExpiry:'2027-09-06', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:750, otherAllowance:800, totalSalary:1550 },
  { fullName:'SHARALYN E', arabicName:'شارالين إي', title:'Labour', nationality:'Filipino', contactNumber:'', emirateId:'', passportNumber:'P81974348', passportIssueDate:'', passportExpiryDate:'2031-11-17', visaExpiryDate:'2027-09-02', labourExpiry:'2027-09-29', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:750, otherAllowance:700, totalSalary:1450 },
  { fullName:'VIVIAN BERSAMINA', arabicName:'فيفيان بيرسامينا', title:'Labour', nationality:'Filipino', contactNumber:'', emirateId:'', passportNumber:'P658440198', passportIssueDate:'', passportExpiryDate:'2031-03-28', visaExpiryDate:'2027-08-30', labourExpiry:'2027-08-01', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:750, otherAllowance:1200, totalSalary:1950 },
  { fullName:'JELLA CRTEGA', arabicName:'جيلا كريتجا', title:'Labour', nationality:'Filipino', contactNumber:'', emirateId:'', passportNumber:'P85534948', passportIssueDate:'', passportExpiryDate:'2031-12-21', visaExpiryDate:'2026-06-18', labourExpiry:'2028-05-30', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:750, otherAllowance:350, totalSalary:1100 },
  { fullName:'JANIS ESPEJO', arabicName:'جانيس إسبخو', title:'Labour', nationality:'Filipino', contactNumber:'', emirateId:'', passportNumber:'P8553521B', passportIssueDate:'', passportExpiryDate:'2031-12-21', visaExpiryDate:'2026-09-30', labourExpiry:'2026-09-23', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:750, otherAllowance:450, totalSalary:1200 },
  { fullName:'RODA MENDOZA', arabicName:'رودا ميندوزا', title:'Labour', nationality:'Filipino', contactNumber:'', emirateId:'', passportNumber:'P3467326B', passportIssueDate:'', passportExpiryDate:'2029-10-07', visaExpiryDate:'2027-11-10', labourExpiry:'2027-11-10', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:750, otherAllowance:350, totalSalary:1100 },
  { fullName:'AIMEE MORENO', arabicName:'إيمي مورينو', title:'Labour', nationality:'Filipino', contactNumber:'', emirateId:'', passportNumber:'P1636212B', passportIssueDate:'', passportExpiryDate:'2029-05-13', visaExpiryDate:'2026-09-19', labourExpiry:'2026-09-17', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:750, otherAllowance:350, totalSalary:1100 },
  { fullName:'ROQYESA FUERTES', arabicName:'روكيسا فويرتيس', title:'Labour', nationality:'Filipino', contactNumber:'', emirateId:'', passportNumber:'P798942C', passportIssueDate:'', passportExpiryDate:'2034-09-15', visaExpiryDate:'2026-10-30', labourExpiry:'2026-10-26', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:750, otherAllowance:350, totalSalary:1100 },
  { fullName:'MOAZZAM MOHAMMED', arabicName:'معظم محمد', title:'Staff', nationality:'Iranian', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2026-09-01', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:2900, totalSalary:4900 },
  { fullName:'HIBA ALI', arabicName:'هبة علي', title:'Staff', nationality:'Iraqi', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2027-10-15', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:2300, totalSalary:4300 },
  { fullName:'AHMED MOHAMED', arabicName:'أحمد محمد', title:'Staff', nationality:'Emirati', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2027-05-20', rtaExpiry:'', joiningDate:'', sponsor:'United Arab Emirates', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:1500, otherAllowance:3500, totalSalary:5000 },
  { fullName:'MARYAM ALI', arabicName:'مريم علي', title:'Staff', nationality:'Iranian', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2027-11-08', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2500, otherAllowance:1500, totalSalary:4000 },
  { fullName:'AHMED HAMID', arabicName:'أحمد حامد', title:'Staff', nationality:'Emirati', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2028-04-29', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:1500, otherAllowance:2500, totalSalary:4000 },
  { fullName:'PUSHPAVATHI YADAV', arabicName:'بوشبافاثي ياداف', title:'Other', nationality:'Indian', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2026-06-02', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2500, otherAllowance:2500, totalSalary:5000 },
  { fullName:'ABDOLLA MASOUD', arabicName:'عبد الله مسعود', title:'Staff', nationality:'Emirati', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2026-09-22', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:1500, otherAllowance:2500, totalSalary:4000 },
  { fullName:'HAMAD JAMAAL', arabicName:'حمد جمال', title:'Staff', nationality:'Emirati', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2026-11-03', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:1500, otherAllowance:2500, totalSalary:4000 },
  { fullName:'ABDALLA OHERAGH', arabicName:'عبد الله أوهيراغ', title:'Staff', nationality:'Emirati', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2027-05-30', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:1500, otherAllowance:3500, totalSalary:5000 },
  { fullName:'BUSHRA ABDULLA', arabicName:'بشرى عبد الله', title:'Staff', nationality:'Emirati', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2027-12-26', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:1500, otherAllowance:3500, totalSalary:5000 },
  { fullName:'MOHAMMAD UMER', arabicName:'محمد عمر', title:'Other', nationality:'Indian', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'2029-01-10', visaExpiryDate:'2028-02-17', labourExpiry:'2028-02-09', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:2500, totalSalary:4500 },
  { fullName:'NESERN AHMAD', arabicName:'نيسيرن أحمد', title:'Teacher', nationality:'Syrian', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2026-10-12', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2500, otherAllowance:2500, totalSalary:5000 },
  { fullName:'ZARMINA KHAN', arabicName:'زارمينا خان', title:'Teacher', nationality:'Pakistani', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2026-10-10', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:2500, totalSalary:4500 },
  { fullName:'AYA SAAD ABDELHAMID', arabicName:'آية سعد عبد الحميد', title:'Teacher', nationality:'Egyptian', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2027-10-10', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:2000, totalSalary:4000 },
  { fullName:'HANAN MOHAMMAD', arabicName:'حنان محمد', title:'Teacher', nationality:'Egyptian', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2028-02-27', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:3700, totalSalary:5700 },
  { fullName:'JINCY JOSEPH', arabicName:'جينسي جوزيف', title:'Teacher', nationality:'Indian', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2026-12-08', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:5900, totalSalary:7900 },
  { fullName:'KAVITHA JOGHEE', arabicName:'كافيثا جوجي', title:'Teacher', nationality:'Indian', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2027-05-05', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:3000, otherAllowance:5600, totalSalary:8600 },
  { fullName:'NOHA MOSTAFA', arabicName:'نهى مصطفى', title:'Teacher', nationality:'Egyptian', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2028-03-03', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:3000, totalSalary:5000 },
  { fullName:'JASMINA BOJADZIC', arabicName:'ياسمين بوجادزيتش', title:'Teacher', nationality:'Other', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2027-09-17', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:3000, otherAllowance:4300, totalSalary:7300 },
  { fullName:'BOHDANA VICKOVA', arabicName:'بهدانا فيكوفا', title:'Teacher', nationality:'Other', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2027-05-02', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:2400, totalSalary:4400 },
  { fullName:'GHADA MOHAMED', arabicName:'غادة محمد', title:'Teacher', nationality:'Egyptian', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2028-02-10', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:2900, totalSalary:4900 },
  { fullName:'SUMAYA ABDALLAH', arabicName:'سمية عبد الله', title:'Teacher', nationality:'Iraqi', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2026-09-21', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2500, otherAllowance:7500, totalSalary:10000 },
  { fullName:'AIMAN MOUHAMMAD', arabicName:'أيمن محمد', title:'Teacher', nationality:'Pakistani', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2027-10-16', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2000, otherAllowance:2000, totalSalary:4000 },
  { fullName:'HEM RANJANI', arabicName:'هيم رانجاني', title:'Teacher', nationality:'Indian', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2028-02-10', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2500, otherAllowance:7500, totalSalary:10000 },
  { fullName:'TINA RANGWANI', arabicName:'تينا رانغواني', title:'Teacher', nationality:'Indian', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'', visaExpiryDate:'', labourExpiry:'2026-09-19', rtaExpiry:'', joiningDate:'', sponsor:'Relative', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:2500, otherAllowance:8800, totalSalary:11300 },
  { fullName:'MARIA LUZ SAMADAN', arabicName:'ماریہ لوز سمدان', title:'Labour', nationality:'Filipino', contactNumber:'', emirateId:'', passportNumber:'', passportIssueDate:'', passportExpiryDate:'2030-08-09', visaExpiryDate:'2027-05-02', labourExpiry:'2027-05-07', rtaExpiry:'', joiningDate:'', sponsor:'Queen International School', licenceNo:'', personImagePath:'', passportImagePath:'', visaImagePath:'', labourCardImagePath:'', basicSalary:750, otherAllowance:350, totalSalary:1100 },
];

export const seedDatabase = async (): Promise<void> => {
  try {
    const existingEmployees = await getAllRecords<Employee>('employees');
    
    if (existingEmployees.length === 0) {
      console.log('Seeding database with Queen International School data...');

      // ⭐ FIX #5: pehle 77 employees EK EK kar ke bane the — har employee par
      // (a) poora list read (code banane ke liye), (b) record write, (c) meta write
      // = ~154 round trips, aur yeh sab startup par. Ab codes local bante hain
      // aur poori list 1-3 multi-path writes mein chali jati hai.
      const startedAt = Date.now();
      const now = new Date().toISOString();
      const records = sampleEmployees.map((empData, i) => ({
        ...empData,
        id: generateId(),
        employeeCode: `QIS${String(i + 1).padStart(4, '0')}`,
        createdAt: now,
        updatedAt: now,
      })) as Employee[];
      const n = await addRecordsBulk<Employee>('employees', records);

      console.log(`Database seeded: ${n} employees in ${Date.now() - startedAt}ms`);
    } else {
      console.log('Database already has', existingEmployees.length, 'employees, skipping seed');
    }
  } catch (err) {
    console.error('Failed to seed database:', err);
  }
};
